### ISSUE TITLE
panvimdoc.lua:76: attempt to concatenate a table value (field 'project')

### ISSUE THREAD

**Issue by jfishe** [kdheepak/panvimdoc#2]
Thank you for putting this together. I don't speak Lua but think I've found a bug when using the YAML metadata instead of --metadata command line option.

The following line at the top of README.md produces the subject error.

```yaml
---
description: 'Filter and convert Vimwiki notes using pandoc'
project: panvimwiki
---
```
The following works as expected.

```bash
cat README.md | pandoc --metadata=project:panvimwiki  \
--metadata=description:'Output vimdoc project  name' \
--lua-filter=build/panvimdoc/scripts/include-files.lua  \
--to=build/panvimdoc/scripts/panvimdoc.lua --shift-heading-level-by=-1  --verbose
```

The fix appears to be `meta.project` should be `stringify(meta.project)` if I'm understanding Lua correctly. I'll start on a pull request as there are several lines besides 76 affected.
