### ISSUE TITLE
Setting up date / date pattern manually

### ISSUE THREAD

**Issue by backdround** [kdheepak/panvimdoc#57]
I've noticed that there is an almost empty commit after any changes that aren't related to documentation:
![image](https://github.com/kdheepak/panvimdoc/assets/17349169/4d3c021e-8ca9-4d51-83f1-8554a8c054a5)
[this commit](https://github.com/backdround/improved-search.nvim/commit/a0cb32735991275a2d7b74234ad2dfbccde55138)

It bothers me a little (I don't like to produce empty commits), and I see possible solutions:
- allow a user to set a `date` manually
- allow a user to set a `date-pattern` manually

Hypothetical `github-actions`' usage with the date:
```yaml
      - name: Generate date
        id: generate_date
        run: echo "date=$(date +%Y)" >> "$GITHUB_OUTPUT"

      - name: panvimdoc
        uses: kdheepak/panvimdoc@main
        with:
          vimdoc: improved-search.nvim
          date: ${{ steps.generate_date.outputs.date }}
```
Hypothetical `github-actions`' usage with the date-pattern:
```yaml
      - name: panvimdoc
        uses: kdheepak/panvimdoc@main
        with:
          vimdoc: improved-search.nvim
          date-pattern: "%Y"
```

I think `date-pattern` seems easier to use.

I would make a PR if you say it makes sense to implement any of the things.

By the way, thank you for the great project!
